{{- range .Values.secrets }}
{{ if eq .type "Opaque" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data:
  {{- range .data }}
  {{ .key }}: {{ .value | b64enc -}}
  {{ end }}
{{ else }}
  # TODO: Add other secret types
{{ end }}
---
{{- end }}
